pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
  # base_views
  path('', base_views.index, name='index'),
  path('<int:question_id>/', base_views.detail, name='detail'),

  # question_views
  path('question/create/', question_views.question_create, name='question_create'),
  path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
  path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

  # answer_views
  path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
  path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
  path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Question(models.Model):
    objects = None
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        }
        labels = {
            'content': '답변 내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()

    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)

    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """
    질문 목록 출력
    """
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    # elif so == 'popular':
    #     question_list = Question.objects.annotate(
    #         num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # {key, value}
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("Hello World")


def detail(request, question_id):
    """
    질문 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}  # {key, value}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control"
                      name="content"
                      id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="while-space: pre-line;">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div>{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            {% if request.user == question.author %}
            <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>

    <h5 class="border_bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="while-space: pre-line;">{{ answer.content|mark }}</div>
            {% if request.user == answer.author %}
            <div class="my-3">
                <a href="{% url 'pybo:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
            </div>
            {% endif %}
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <textarea {% if not user.is_authenticated %}disabled{% endif %}
                name="content" id="content" rows="10", class="form-control"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">
</form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
  $(document).ready(function() {
    $(".delete").on('click', function() {
      if(confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data('uri');
      }
    });
  });
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border_bottom pb-2">질문 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
          {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" name="subject" id="subject"
             value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
<!--    {{ form.as_p }}-->
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
  <div class="row justify-content-between my-3">
    <div class="col-2">
      <select class="form-control so">
        <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
<!--        <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>-->
        <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
      </select>
    </div>
    <div class="col-4 input-group">
      <input type="text" class="form-control kw"
             value="{{kw|default_if_none:'' }}">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
      </div>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr class="text-center thead-dark">
        <th>번호</th>
        <th style="width:50%">제목</th>
        <th>작성자</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
    {% if question_list %}
    {% for question in question_list %}
    <tr class="text-center">
      <td>
        {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
      </td>
      <td class="text-left">
        <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
        {% if question.answer_set.count > 0 %}
        <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
        {% endif %}
      </td>
      <td>{{ question.author.username }}</td>
      <td>{{ question.create_date }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
      <td colspan="3">항목이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
  </table>
<!-- 페이징 처리 -->
  <ul class = "pagination justify-content-center">
<!-- 이전 페이지 -->
    {% if question_list.has_previous %}
    <li class="page-item">
      <a class="page-link"
         data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
  {% endif %}
<!-- 페이지 리스트 -->
  {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
      {% if page_number == question_list.number %}
      <li class="page-item active" aria-current="page">
        <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
      </li>
      {% endif %}
    {% endif %}
  {% endfor %}
<!-- 다음 페이지 -->
  {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link"
         data-page="{{ question_list.next_page_number }}" href="#">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
<!-- 페이징 처리 끝 -->
  <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
  <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function() {
  $(".page-link").on('click', function() {
    $("#page").val($(this).data("page"));
    $("#searchForm").submit();
  });

  $("#btn_search").on('click', function() {
    $("#kw").val($(".kw").val());
    $("#page").val(1);
    $("#searchForm").submit();
  });

  $(".so").on('change', function() {
    $("#so").val($(this).val());
    $("#page").val(1);
    $("#searchForm").submit();
  });
});
</script>
{% endblock %}